SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NULL,
    name VARCHAR(255) NULL,
    provider VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255) NULL,
    created_at DATETIME NULL
);

CREATE TABLE urls (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    original_url VARCHAR(2048) NOT NULL,
    short_code VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NULL,
    clicks INT DEFAULT 0,
    created_at DATETIME NULL,
    CONSTRAINT FK_urls_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
